package com.wiiudev.gecko.pointer.swing;

public enum PersistentSetting
{
	LAST_ADDED_FILE_PATH,
	PARSE_ENTIRE_FOLDER,
	LAST_ADDED_STARTING_ADDRESS,
	POINTER_SEARCH_DEPTH,
	POINTER_VALUE_ALIGNMENT,
	POINTER_ADDRESS_ALIGNMENT,
	MAXIMUM_MEMORY_CHUNK_SIZE,
	MAXIMUM_POINTERS_COUNT,
	MAXIMUM_OFFSET,
	MINIMUM_POINTER_ADDRESS,
	POINTER_RESULTS_PAGE_SIZE,
	LAST_POINTER_OFFSETS,
	ADDRESS_SIZE,
	ALLOW_NEGATIVE_OFFSETS,
	SINGLE_MEMORY_DUMP_METHOD,
	GENERATE_POINTER_MAPS,
	WRITE_POINTERS_TO_FILE_SYSTEM,
	BASE_OFFSET_RANGE,
	EXCLUDE_POINTER_CYCLES,
	USE_NATIVE_POINTER_ENGINE,
	STARTING_BASE_ADDRESS,
	END_BASE_ADDRESS
}
